name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
    - run: npm install
    - run: npm install -g @vscode/vsce
    - run: vsce package --out ios-debug-companion.vsix
    - uses: actions/upload-artifact@v3
      with:
        path: ios-debug-companion.vsix
